version: "3"
services:
  qq-bot-midou:
    build:
      context: ./
      dockerfile: Dockerfile
    image: qq-bot-midou
    container_name: qq-bot-midou
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
      - /root/qq-bot-midou/qqbotsecert.yml:/qqbotsecert.yml
      - /root/qq-bot-midou/minecraft_server_status_config.yml:/minecraft_server_status_config.yml
    restart: always