[project]
name = "qq-bot"
version = "0.1.0"
description = "qq-bot"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "QQ", module_name = "nonebot.adapters.qq" }
]
plugins = []
plugin_dirs = ["plugins"]
builtin_plugins = []
